// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
        "time"
)

const TableNamePeerTrace = "peer_trace"

// PeerTrace mapped from table <peer_trace>
type PeerTrace struct {
        IP           string    `gorm:"column:ip;not null" json:"ip"`
        InfoHash     []uint8   `gorm:"column:info_hash;not null" json:"info_hash"`
        LastSeenTime time.Time `gorm:"column:last_seen_time;default:(CURRENT_TIMESTAMP AT TIME ZONE 'UTC" json:"last_seen_time"`
}

// TableName PeerTrace's table name
func (*PeerTrace) TableName() string {
        return TableNamePeerTrace
}
